package uk.ac.ebi.pride.spectracluster.keys;


/**
 * uk.ac.ebi.pride.spectracluster.keys.UnStableChargeBinMZKey
 * key represents charge bin number, group and precursor mz
 * used for stable clusters guaranteed to sort late
 * must sort early
 * User: Steve
 * Date: 8/13/13
 * key object using charge,mz,peak
 */
public class UnStableBinMZKey extends StableBinMZKey implements Comparable<StableBinMZKey>,IKeyable {

    public static final String SORT_PREFIX = "|"; // ascii decimal guaranteed to sort EARLY

    public UnStableBinMZKey(int pBin, int pGroup, double pPrecursorMZ) {
        super(pBin, pGroup, pPrecursorMZ);
    }


    /**
     * use  StableChargeBinMZKey.buildKey WHICH FIGURES OUT OF THE KEY US STABLE OR UNSTABLE
     * @param str  !null String generated by toString
     */
    public UnStableBinMZKey(String str) {
        super(str);
    }

    protected String getSortPrefix()
    {
        return  SORT_PREFIX;
    }


}
